#!/usr/bin/env bash
# install Nginx on the server
sudo apt-get install nginx
ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
#sudo systemctl reload nginx
apt-get install -y nginx