#!/usr/bin/env bash
# redirect to another page
redirection_config="location = /redirect_me {\n\
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\
}"
sudo sed -i "/server_name _;/a $redirection_config" /etc/nginx/sites-available/default
sudo service nginx restart
