#!/usr/bin/env bash
# redirect to another page
sudo sed -i '/server_name _;/a \
    location = /redirect_me { \
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
    }' /etc/nginx/sites-available/default

sudo service nginx restart
