#!/usr/bin/env bash
# redirect to another page

# sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html

redirection_config="location = /redirect_me/ {\n\
    rewrite ^ /https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;
}"
# sudo echo $redirection_config >> /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/a $redirection_config" /etc/nginx/sites-available/default
sudo service nginx restart
